name: Deploy to FTP

on:
  push:
    branches:
      - master

jobs:
  retry_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Retry FTP Deployment
      run: |
        n=0
        until [ $n -ge 5 ]
        do
          echo "Attempt $n"
          if (curl --ftp-pasv -T ./publish/* -u ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }} ftp://${{ secrets.FTP_SERVER }}/${{ secrets.DEPLOY_PATH }}/); then
            break
          fi
          n=$((n+1))
          sleep 10
        done
      continue-on-error: true

  deploy:
    runs-on: ubuntu-latest
    needs: retry_deploy  # Wait for the retry job to complete

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'  # Replace with your desired .NET Core version

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the project
      run: dotnet publish -c Release -o publish

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@master
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.DEPLOY_PATH }}/   # Replace with your desired FTP directory path
        local-dir: './publish/'  # The directory to upload to FTP, change accordingly
        exclude: '**/.git*'
