name: Deploy to FTP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'  # Replace with your desired .NET Core version

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the project
      run: dotnet publish -c Release -o publish

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@master
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.DEPLOY_PATH }}/   # Replace with your desired FTP directory path
        local-dir: './publish/'  # The directory to upload to FTP, change accordingly
        exclude: '**/.git*'
